<form action="" method="post" autocomplete="off">
    <h2>Ajouter un utilisateur</h2>
    <dl>
        <dt><label for="username">Nom d'utilisateur</label></dt>
        <dd>
            <input type="text" id="username" name="username" value="<?php
                echo htmlspecialchars($user->getUsername());
            ?>" />
            <?php if (isset($errors["username"])) : ?>
            <p class="error"><?php echo $errors["username"]; ?></p>
            <?php endif; ?>
        </dd>
        <dt><label for="password">Mot de passe</label></dt>
        <dd>
            <input type="password" id="password" name="password" />
            <?php if (isset($errors["password"])) : ?>
            <p class="error"><?php echo $errors["password"]; ?></p>
            <?php endif; ?>
        </dd>
        <dt><label for="confirmPassword">Confirmez le mot de passe</label></dt>
        <dd>
            <input type="password" id="confirmPassword" name="confirmPassword" />
            <?php if (isset($errors["confirmPassword"])) : ?>
            <p class="error"><?php echo $errors["confirmPassword"]; ?></p>
            <?php endif; ?>
        </dd>
        <dt><label for="quota">Nombre d'alertes maximum (0 pour illimité)</label></dt>
        <dd>
            <input type="text" id="quota" name="quota" value="0"/>
            <?php if (isset($errors["quota"])) : ?>
            <p class="error"><?php echo $errors["quota"]; ?></p>
            <?php endif; ?>
        </dd>
    </dl>
    <p><input type="submit" value="Enregistrer" />
        | <a href="?mod=admin&amp;a=users">annuler</a></p>
</form>
